experiment: &EXP_NAME batch_delete

raiz: '/mnt/c/Users/Yesica/Documents/gafricano/finetuning-master/results/'

ckpt_path: !join [./checkpoints/, *EXP_NAME]
metric: auc
outage: 0
dataset:
  cases: '/mnt/c/Users/Yesica/Downloads/Wu-s-network-master/sample_data/wu_cases_test.csv'
  controls: '/mnt/c/Users/Yesica/Downloads/Wu-s-network-master/sample_data/wu_controls_test.csv'
  val_size: 0.4
  transformations:
    flip_view: 'R'
    contours: False
    clahe: True
    pixel_noise: 0.005
    rotation: 4
    to_tensor: True
    max_crop_noise: !!python/tuple [70, 70]
    max_crop_size_noise: 70


cropping:
  cases: '/mnt/c/Users/Yesica/Downloads/Wu-s-network-master/sample_output/data_cases.pkl'
  controls: '/mnt/c/Users/Yesica/Downloads/Wu-s-network-master/sample_output/data_cases.pkl'

train:
  num_epochs: 3
  unfreeze: 50
  batch_size: &BATCH 4
  augmentations: True

val:
  batch_size: *BATCH
  augmentations: False

logger:
  state: on
  path: !join [./runs/, *EXP_NAME]

model:
  variant: 'view_wise'
  batch_norm: False
  use_heatmaps: False
  finetuning: True
  flayer: False
  extended_model: False
  GPU_use: "cuda:0"
  image_weights_path: '/mnt/c/Users/Yesica/Downloads/Wu-s-network-master/models/sample_image_model.p'
  heatmap_weights_path: '/mnt/c/Users/Yesica/Downloads/Wu-s-network-master/models/sample_imageheatmaps_model.p'
  dropout:
    state: off
    p: 0.6
parameters:
  image_path_cases: '/mnt/c/Users/Yesica/Downloads/Wu-s-network-master/sample_output/cropped_images_cases'
  image_path_controls: '/mnt/c/Users/Yesica/Downloads/Wu-s-network-master/sample_output/cropped_images_cases'
  heatmaps_path_cases: '/mnt/c/Users/Yesica/Downloads/Wu-s-network-master/sample_output/heatmaps_cases'
  heatmaps_path_controls: '/mnt/c/Users/Yesica/Downloads/Wu-s-network-master/sample_output/heatmaps_controls'

optimizer:
  variant: 'adam'
  lr: 0.00001
  weight_decay: '10**(-4.5)'

scheduler:
    gamma: 1.0
    step: 10
 

